# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "sphersgeo"
version = "0.2.0"
edition = "2024"
description = "object-oriented spherical geometry"
readme = "README.md"
repository = "https://github.com/spacetelescope/sphersgeo"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib"]
name = "sphersgeo"

[dependencies]
kiddo = "5.2.2"
ndarray = { version = "0.17.1", features = ["rayon"], optional = true }
numpy = { version = "0.28.0", optional = true }
pyo3 = { version = "0.28.3", features = ["abi3-py311"], optional = true }

[features]
default = ["py"]
ndarray = ["dep:ndarray"]
py = ["dep:numpy", "dep:pyo3", "ndarray"]
