[project]
name = "sphersgeo"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Rust",
]
dependencies = ["numpy"]
dynamic = [
  "description",
  "license",
  "readme",
  "urls",
  "version",
]

[dependency-groups]
test = ["gwcs", "pytest"]

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.cibuildwheel]
build = "cp311-*"
test-requires = ["abi3audit"]
test-command = "python -c 'from sphersgeo import SphericalPoint, MultiSphericalPoint, ArcString, MultiArcString, SphericalPolygon, MultiSphericalPolygon' && abi3audit --strict --report dist/*.whl"

[tool.maturin]
features = ["pyo3/extension-module", "py"]
python-source = "src/python/"
