[project]
name = "sphersgeo"
requires-python = ">=3.12"
authors = [{ name = "Zach Burnett", email = "zburnett@stsci.edu" }]
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Rust",
]
dependencies = ["numpy>=2.1"]
dynamic = [
  "description",
  "license",
  "readme",
  "urls",
  "version",
]

[dependency-groups]
docs = ["furo", "sphinx", "sphinx-autoapi", "sphinx_inline_tabs", "towncrier"]
test = ["gwcs", "pytest", "pytest-helpers-namespace"]

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.cibuildwheel]
build = "cp312-*"
test-requires = ["abi3audit"]
test-command = "python -c 'from sphersgeo import SphericalPoint, MultiSphericalPoint, ArcString, MultiArcString, SphericalPolygon, MultiSphericalPolygon' && abi3audit --strict --report dist/*.whl"

[tool.maturin]
features = ["pyo3/extension-module", "py"]
python-source = "src/python/"
